/* 
This code calculates the averages for the output file generated by the NBF code.
*/

#include <stdio.h>
#include <string.h>
#include <stdlib.h>

#define N_TH 4;
#define N_TX 4;


//This shell script is helpful for the analyse
#define SHELLSCRIPT "\
#/bin/bash \n\
export IFS=\";\"  \n\
grep -v \"#\" 1.2.result |grep -v \"Duration\" |grep -v \" \"|grep -i \";\" > c.file  \n\
"
/* This struct stores the statistics variables for LibTM */
struct Statistics{
    double  Duration;
    int Commits;
    int N_DLK_RAW;
    int N_DLK_WAR;
    int N_DLK_WAW;
    int N_INV;
    double N_ABR;
    double T_WT_ALL;
    double AbRatio;
    double WrRatio;
};

/* This struct stores the Thread X Transaction values */
struct Thread{
    int id;
    int Tx_id;
    struct Statistics Values[30];
};

/* Print values for ALL the transactions and Threads */
int print(struct Thread TT[N_TX][N_TH]){
    int count=0;
    int test;
    int thread,transaction;
    
    for (transaction=0;transaction < N_TX ; transaction++)
    {
        for(thread=0;thread < N_TH; thread++)
        {
            /* Due txn 2 and 3 are executed 10X more than 0 and 1 */
            if(transaction < 2)
                test=3;
            else
                test=30;
            
            for (count=0;count < test ; count++)
            {
                printf("Txn:%d Thread:%d",transaction,thread);
                printf("Duration %4.4f - ",TT[transaction][thread].Values[count].Duration);
                printf("Commits %d",TT[transaction][thread].Values[count].Commits);
                printf("RAW - %d",TT[transaction][thread].Values[count].N_DLK_RAW);
                printf("WAR %d",TT[transaction][thread].Values[count].N_DLK_WAR);
                printf("WAW %d",TT[transaction][thread].Values[count].N_DLK_WAW);
                printf("INV %d",TT[transaction][thread].Values[count].N_INV);
                printf("ABR %4.4f",TT[transaction][thread].Values[count].N_ABR);
                printf("Waiting %4.4f",TT[transaction][thread].Values[count].T_WT_ALL);
                printf("ABRatio %4.4f",TT[transaction][thread].Values[count].AbRatio);
                printf("Write Ratio %4.4f",TT[transaction][thread].Values[count].WrRatio);
                printf ("\n");
            }
        }
    }
    return 0;
}

/* Calculates the Average for All Threads X Transactions */
struct Thread average(struct Thread TT[N_TX][N_TH])
{
    struct Thread avg[N_TX][N_TH];
    int count=0;
    int test;
    int thread,transaction;
    
    for (transaction=0;transaction < N_TX ; transaction++)
    {
        for(thread=0;thread < N_TH; thread++)
        {
            if(transaction < 2)
                test=3;
            else
                test=30;
            
            for (count=0;count < test ; count++)
            {
                avg[transaction][thread].Values[0].Duration += TT[transaction][thread].Values[count].Duration;
                avg[transaction][thread].Values[0].Commits  += TT[transaction][thread].Values[count].Commits;
                avg[transaction][thread].Values[0].N_DLK_RAW += TT[transaction][thread].Values[count].N_DLK_RAW;
                avg[transaction][thread].Values[0].N_DLK_WAR += TT[transaction][thread].Values[count].N_DLK_WAR;
                avg[transaction][thread].Values[0].N_DLK_WAW += TT[transaction][thread].Values[count].N_DLK_WAW;
                avg[transaction][thread].Values[0].N_INV += TT[transaction][thread].Values[count].N_INV;
                avg[transaction][thread].Values[0].N_ABR += TT[transaction][thread].Values[count].N_ABR;
                avg[transaction][thread].Values[0].T_WT_ALL += TT[transaction][thread].Values[count].T_WT_ALL;
                avg[transaction][thread].Values[0].AbRatio  += TT[transaction][thread].Values[count].AbRatio;
                avg[transaction][thread].Values[0].WrRatio += TT[transaction][thread].Values[count].WrRatio;
                
            }
            
            avg[transaction][thread].Values[0].Duration = (avg[transaction][thread].Values[0].Duration / test);
            avg[transaction][thread].Values[0].Commits  = avg[transaction][thread].Values[0].Commits / test;
            avg[transaction][thread].Values[0].N_DLK_RAW = avg[transaction][thread].Values[0].N_DLK_RAW / test;
            avg[transaction][thread].Values[0].N_DLK_WAR = avg[transaction][thread].Values[0].N_DLK_WAR / test;
            avg[transaction][thread].Values[0].N_DLK_WAW = avg[transaction][thread].Values[0].N_DLK_WAW / test;
            avg[transaction][thread].Values[0].N_INV = avg[transaction][thread].Values[0].N_INV / test;
            avg[transaction][thread].Values[0].N_ABR = avg[transaction][thread].Values[0].N_ABR / test;
            avg[transaction][thread].Values[0].T_WT_ALL = avg[transaction][thread].Values[0].T_WT_ALL / test;
            avg[transaction][thread].Values[0].AbRatio  = avg[transaction][thread].Values[0].AbRatio / test;
            avg[transaction][thread].Values[0].WrRatio = avg[transaction][thread].Values[0].WrRatio / test;
            
            /* Print the average value ###This can be later directed to a file */
            printf("Txn:%d - Thread:%d - ",transaction,thread);
            printf("Duration %4.4f - ",avg[transaction][thread].Values[0].Duration);
            printf("Commits %d - ",avg[transaction][thread].Values[0].Commits);
            printf("RAW - %d - ",avg[transaction][thread].Values[0].N_DLK_RAW);
            printf("WAR %d - ",avg[transaction][thread].Values[0].N_DLK_WAR);
            printf("WAW %d - ",avg[transaction][thread].Values[0].N_DLK_WAW);
            printf("INV %d - ",avg[transaction][thread].Values[0].N_INV);
            printf("ABR %4.4f - ",avg[transaction][thread].Values[0].N_ABR);
            printf("Waiting %4.4f - ",avg[transaction][thread].Values[0].T_WT_ALL);
            printf("ABRatio %4.4f - ",avg[transaction][thread].Values[0].AbRatio);
            printf("Write Ratio %4.4f\n",avg[transaction][thread].Values[0].WrRatio);
        }
        
    }
  return avg[N_TX][N_TH];
}

int main()
{
    //system(SHELLSCRIPT);
    struct Thread TT[N_TX][N_TH];
    
    int Th_id,Tx_id;  //Counter for transaction and Threads
    int count=0;
    char str[200];
    char * str1;
    FILE *fp;
    
    /* c.file is generated by the testbench.sh script */
    fp = fopen("c.file", "r");
    while(fscanf(fp, "%s", str) == 1)
    {
        /* All the code below extract the c.file using the ";" as separator and loads it into the vectors for Txn and Threads */
        
        str1=strtok(str,";");  //Define separatos
        
        while (str1 != NULL)
        {
            if(atoi(str1) == 0 || atoi(str1) == 1 || atoi(str1) == 2 || atoi(str1) == 3 )
                Tx_id = atoi(str1);  //Define Transaction ID
            
            str1 = strtok (NULL, ";");
            
            if(atoi(str1) == 0 || atoi(str1) == 1 || atoi(str1) == 2 || atoi(str1) == 3 )
                Th_id = atoi(str1); // Define Thread ID
            
            str1 = strtok (NULL, ";");
            TT[Tx_id][Th_id].Values[count].Duration = atof(str1);
            
            str1 = strtok (NULL, ";");
            TT[Tx_id][Th_id].Values[count].Commits = atoi(str1);
            
            str1 = strtok (NULL, ";");
            TT[Tx_id][Th_id].Values[count].N_DLK_RAW=atoi(str1);
            
            str1 = strtok (NULL, ";");
            TT[Tx_id][Th_id].Values[count].N_DLK_WAR=atoi(str1);
            
            str1 = strtok (NULL, ";");
            TT[Tx_id][Th_id].Values[count].N_DLK_WAW=atoi(str1);
            
            str1 = strtok (NULL, ";");
            TT[Tx_id][Th_id].Values[count].N_INV=atoi(str1);
            
            str1 = strtok (NULL, ";");
            TT[Tx_id][Th_id].Values[count].N_ABR=atof(str1);
            
            str1 = strtok (NULL, ";");
            TT[Tx_id][Th_id].Values[count].T_WT_ALL=atof(str1);
            
            str1 = strtok (NULL, ";");
            TT[Tx_id][Th_id].Values[count].AbRatio=atof(str1);
            
            str1 = strtok (NULL, ";");
            TT[Tx_id][Th_id].Values[count].WrRatio=atof(str1);
            
            str1 = strtok (NULL, ";"); // This value is tested in the loop ...
            
            /* As some txn have different number of executions in loop, the count has to be variable as follow */
            if(Tx_id < 2 && count ==2 ){
                count=0;
                continue;
            }
            if(Tx_id >=2 && count ==29){
                count=0;
            }
            else
             count++;
            
        }
    }
    
    fclose(fp);
    
    //Calculates and prints the Average for ALL txn X Threads
    average(TT);
    
    //Print Function ** As this function prints ALL the txn and Thread, For now it's used only validate the results
    //print(TT);
    
    return 0;
}
